# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - develop

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: 00c7454b-9d6f-477d-a0b8-2c31ff700218
              repository: stayfunFrontend
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: buildAndPush
              dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
